[package]
name = "pw_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
heapless = "0.7.17"
postcard = { version = "1.1.1", features = ["alloc"] }
rand_core = "0.6.3"
rs_n_bit_words = "0.1.3"
rs_sha512 = "0.1.3"
serde = "1.0.218"
