[package]
name = "pw_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
heapless = "0.7.17"
rand_core = "0.6.3"
rs_n_bit_words = "0.1.3"
rs_sha512 = "0.1.3"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
